### ISSUE TITLE
Make Asciidoctor interface more directly configurable

### ISSUE THREAD

**Issue by briandominick** [briandominick/liquidoc-gem#20]
There are already several shortcomings to the Asciidoctor gem call in LiquiDoc's `render` operation. Make sure user's don't lose any of the power over Asciidoctor by sending their build orders through LiquiDoc. We're trying to make it way easier to do some things than it is now, and even if other aspects need alteration (like attributes handling), we certainly should not be sacrificing any Asciidoctor functionality. This will have include invoking extensions, as well. No major tradeoffs.

**Comment by briandominick** [comment]
Render stages should accept a list of required extensions.

```yaml
  builds:
    - output: _build/user-guide.pdf
      doctype: book
      attributes:
        sample_attr: test value
      extensions:
        - git-metadata-preprocessor
        - shell-session-treeprocessor
```
