### ISSUE TITLE
Enable global AsciiDoc attribute setting in YAML file

### ISSUE THREAD

**Issue by briandominick** [briandominick/liquidoc-gem#3]
In order that global settings and can be established in more neutral formats, users should be able to establish AsciiDoc variables (called "attributes") via a semi-structured flat file outside the AsciiDoc domain. So a YAML file can contain settings, e.g.:
```yaml
attributes:
  imagesdir: images
  testsetting: true
```
This will be fed to Asciidoctor during the asciidoctor gem call from LiquiDoc.
