### ISSUE TITLE
Extend YAML parsing with dynamic & flattened vars

### ISSUE THREAD

**Issue by briandominick** [briandominick/liquidoc-gem#31]
The way @mojavelinux has extended YAML parsing in the asciidoctor-pdf gem is pretty amazing. The [code is here](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/theme_loader.rb#L62) and the [DSL documentation is here](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#language-overview). This is a really simple and elegant enhancement. It lets you build cumulative variable values _and_ it enables unique, flattened variables formed from the nested structure.

```yaml
domain: codewriting.org
uri:
  base: http://$domain
  base_ssl: https://$domain
  blog: $uri_base/blog
```
Which can then produce variables that are called as such in AsciiDoc: `{uri_blog}`.

This should probably be a module inside LiquiDoc until it's ready to stand on its own, then maybe spin off its own gem to share this functionality more broadly.
