### ISSUE TITLE
Enable "routing" or "routines" to filter steps in a config file

### ISSUE THREAD

**Issue by briandominick** [briandominick/liquidoc-gem#33]
To go along with #14, once we have optional labels for the steps in a config file, we should be able to allow preset configurations of them. For instance:

```yaml
routines:
  - name: no-pdf
    skip:
      - publish-book
      - publish-menu
  - name: preproc
     only:
      - migrate-assets
      - parse-menu
  - name: jekyll-only
      - config_preproc
      - jekyll-build
```
This may require a way to handle build-steps, which is probably most of what we'd want to filter. If they're named, we can list them as sub-steps of their parent using `publish-book:pdf`.
