### ISSUE TITLE
Restructure LiquiDoc config file

### ISSUE THREAD

**Issue by briandominick** [briandominick/liquidoc-gem#4]
It doesn't actually make sense to enforce an order for LiquiDoc build actions. Users should be able to simply list actions in a configuration.

We have a few action types we want to establish:

* *parse* data from semi-structured files using Liquid templates
* *migrate* directories and files so we can have assets where they're needed druring the build
* *render* documents with Asciidoctor, such as PDFs, slide decks, HTML pages, etc
* *deploy* documents and content to the Web using Jekyll/Travis and other CI/CD tools

A user may establish a configuration file like so:
```yaml
- action: parse
  source: mydata.json
  builds:
    - template: _templates/mytemplate.asciidoc
    - output: build/includes/mystuff.adoc
- action: migrate
  source: assets/
  target: build/assets/
- action: migrate
  source: content/myindex.adoc
  target: build/
- action: render
  data: _data/asciidoctor.yml
  source: build/myindex.adoc
  builds:
    - type: pdf
    - output: build/output/mybook.pdf
    - attributes:
      - environment: internal
- action: deploy
  config: _configs/jekyll.yml
```
Each top-level item can be listed in any order, though the above would be typical.
