### ISSUE TITLE
Enable sorting of data on the fly

### ISSUE THREAD

**Issue by briandominick** [briandominick/liquidoc-gem#6]
We can ingest data from source files, but we cannot yet reorder data before spitting it back out. At the very least, we need to be able to sort by any top-level "column".

```yaml
- action: parse
  source: _data/ourdata.xml
  builds: 
    - template: _templates/liquid/ourdata.markdown
      output: builds/docs/ourdata.md
      sort:
        column: field_3
        order: asc
```
We'll eventually want more of a SQL style management with group-by functionality, multi-column conditional operations, data filtering, etc. For now, let's consider this proof of concept before we make the configurations too complex.
